version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-1-4-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ojazgo9knqin"
s3_prefix = "todo-list-aws-1-4"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []