version = 0.1
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-1-4-production"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ojazgo9knqin"
s3_prefix = "todo-list-aws-1-4"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []